import {score,statusLabels} from './domain.js';
import {stageLabel} from './tournaments.js';
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=value=>value?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'9999';
const time=value=>value?new Date(value).toLocaleTimeString('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'}):'รอยืนยันเวลา';
const crest=t=>/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(t?.public_logo||'')?`<img alt="" src="${t.public_logo}">`:`<span class="fixture-crest-fallback" aria-hidden="true">${escape((t?.name||'?').slice(0,2))}</span>`;
function select(name,label,rows,value){return `<label class="fixture-filter"><span>${label}</span><select data-fixture-filter="${name}">${rows.map(([id,text])=>`<option value="${escape(id)}" ${String(id)===String(value)?'selected':''}>${escape(text)}</option>`).join('')}</select></label>`;}
export function filteredFixtures(data,filters){return data.matches.filter(m=>(!filters.round||String(m.round)===filters.round)&&(!filters.team||m.home_id===filters.team||m.away_id===filters.team)&&(!filters.status||m.status===filters.status)).sort((a,b)=>(a.kickoff||'9999').localeCompare(b.kickoff||'9999')||a.round-b.round||String(a.id).localeCompare(String(b.id)));}
export function fixturesHTML(data,filters){
 const rounds=[...new Set(data.matches.map(m=>m.round))].sort((a,b)=>a-b),matches=filteredFixtures(data,filters),groups=new Map();
 for(const m of matches){const key=dateKey(m.kickoff);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m);}
 return `<section class="fixture-board"><div class="fixture-heading"><div><span class="fixture-eyebrow">MATCH CENTRE</span><h2>โปรแกรมและผลการแข่งขัน</h2><p>${escape(data.competition.name)}${data.competition.season?' · ฤดูกาล '+escape(data.competition.season):''}</p></div><span class="fixture-total">${matches.length} คู่แข่งขัน</span></div><div class="fixture-filters">${select('round','นัดที่ / รอบการแข่งขัน',[['','ทุกรอบ'],...rounds.map(r=>[r,'รอบ '+r])],filters.round)}${select('team','ทีม',[['','ทุกทีม'],...data.teams.map(t=>[t.id,t.name])],filters.team)}${select('status','สถานะ',[['','ทุกสถานะ'],...Object.entries(statusLabels)],filters.status)}<button type="button" data-reset-fixtures>ล้างตัวกรอง ↺</button></div>${[...groups.values()].map(rows=>`<section class="fixture-day"><header class="fixture-date"><span class="fixture-calendar" aria-hidden="true">▦</span><h3>${rows[0].kickoff?new Date(rows[0].kickoff).toLocaleDateString('th-TH',{timeZone:'Asia/Bangkok',weekday:'long',day:'numeric',month:'long',year:'numeric'}):'ยังไม่กำหนดวันแข่งขัน'}</h3><span>${rows.length} คู่</span></header>${rows.map(m=>{
 const home=data.teams.find(t=>t.id===m.home_id),away=data.teams.find(t=>t.id===m.away_id),s=score(m,data.events),played=['live','finished'].includes(m.status);
 return `<article class="fixture-row ${m.status==='live'?'fixture-live':''}"><div class="fixture-meta"><span class="fixture-round">${escape(stageLabel(m))}</span><span class="fixture-status ${m.status==='live'?'is-live':''}">${escape(statusLabels[m.status]||m.status)}</span></div><div class="fixture-pair"><div class="fixture-team fixture-home"><strong>${escape(home?.name||'—')}</strong>${crest(home)}</div><div class="fixture-result"><strong class="${played?'fixture-score':'fixture-kickoff'}">${played?s.home+' : '+s.away:time(m.kickoff)}</strong><small>${m.status==='finished'?'เต็มเวลา':m.status==='live'?'กำลังแข่งขัน':'เวลาแข่งขัน'}</small></div><div class="fixture-team fixture-away">${crest(away)}<strong>${escape(away?.name||'—')}</strong></div></div><div class="fixture-bottom"><span class="fixture-venue">${escape(m.venue||'ยังไม่ระบุสนาม')}</span><span data-clock="${escape(m.id)}"></span><button data-match="${escape(m.id)}" aria-label="รายละเอียด ${escape(home?.name)} พบ ${escape(away?.name)}">รายละเอียดการแข่งขัน <span aria-hidden="true">→</span></button></div></article>`;
 }).join('')}</section>`).join('')||'<div class="empty fixture-empty">ไม่พบคู่แข่งขันตามตัวกรองที่เลือก</div>'}</section>`;
}
